import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const stamp = new Date().toISOString().replaceAll(/[:.]/g, "-");
const backupDir = resolve("backups", `drill-${stamp}`);
const d1Dump = join(backupDir, "d1.sql");
const d1DataDump = join(backupDir, "d1-data.sql");
const orderedDataDump = join(backupDir, "d1-data-ordered.sql");
const report = join(backupDir, "report.md");
const restorePersistDir = join(backupDir, "restore-d1");

mkdirSync(backupDir, { recursive: true });

const steps = [];

step("export local D1 dump", () =>
  run("pnpm", [
    "exec",
    "wrangler",
    "d1",
    "export",
    "DB",
    "--local",
    "--output",
    d1Dump,
    "--skip-confirmation",
  ]),
);

step("export local D1 data", () =>
  run("pnpm", [
    "exec",
    "wrangler",
    "d1",
    "export",
    "DB",
    "--local",
    "--no-schema",
    "--output",
    d1DataDump,
    "--skip-confirmation",
  ]),
);

step("verify D1 dump exists", () => {
  if (!existsSync(d1Dump)) {
    throw new Error(`Missing dump: ${d1Dump}`);
  }
  const dump = readFileSync(d1Dump, "utf8");
  if (!dump.includes("CREATE TABLE") && !dump.includes("INSERT INTO")) {
    throw new Error("D1 dump does not look like a SQL backup.");
  }
});

step("prepare ordered D1 data restore file", () => {
  const dataDump = readFileSync(d1DataDump, "utf8");
  const orderedTables = [
    "users",
    "memos",
    "attachments",
    "memo_relations",
    "settings",
    "shares",
  ];
  const lines = ["PRAGMA defer_foreign_keys=TRUE;"];

  for (const table of orderedTables) {
    const tableInserts = dataDump
      .split("\n")
      .filter(
        (line) =>
          line.startsWith(`INSERT INTO "${table}" `) ||
          line.startsWith(`INSERT INTO \`${table}\` `),
      );
    lines.push(...tableInserts);
  }

  writeFileSync(orderedDataDump, `${lines.join("\n")}\n`);
});

step("create isolated restore schema from migrations", () =>
  run("pnpm", [
    "exec",
    "wrangler",
    "d1",
    "migrations",
    "apply",
    "DB",
    "--local",
    "--persist-to",
    restorePersistDir,
  ]),
);

step("restore D1 data into isolated local database", () =>
  run("pnpm", [
    "exec",
    "wrangler",
    "d1",
    "execute",
    "DB",
    "--local",
    "--persist-to",
    restorePersistDir,
    "--file",
    orderedDataDump,
    "--yes",
  ]),
);

step("verify restored D1 schema", () =>
  run("pnpm", [
    "exec",
    "wrangler",
    "d1",
    "execute",
    "DB",
    "--local",
    "--persist-to",
    restorePersistDir,
    "--command",
    "SELECT COUNT(*) AS memo_count FROM memos;",
  ]),
);

step("list remote D1 migrations", () =>
  run("pnpm", [
    "exec",
    "wrangler",
    "d1",
    "migrations",
    "list",
    "DB",
    "--remote",
  ]),
);
step("verify R2 bucket exists", () => {
  const result = run("pnpm", ["exec", "wrangler", "r2", "bucket", "list"], {
    capture: true,
  });
  if (!result.stdout.includes("flaremo-attachments")) {
    throw new Error("R2 bucket flaremo-attachments was not found.");
  }
  process.stdout.write(result.stdout);
});

writeFileSync(
  report,
  [
    "# FlareMo Backup Drill",
    "",
    `- Created at: ${new Date().toISOString()}`,
    `- D1 dump: ${d1Dump}`,
    `- D1 data restore file: ${orderedDataDump}`,
    `- Restore target: ${restorePersistDir}`,
    "",
    "## Steps",
    "",
    ...steps.map((item) => `- ${item}`),
    "",
    "## Restore Notes",
    "",
    "1. Create a fresh D1 database and R2 bucket.",
    "2. Apply FlareMo migrations to the fresh D1 database.",
    "3. Restore D1 data from the ordered data restore file generated by this drill.",
    "4. Restore R2 objects with an S3-compatible sync tool such as rclone.",
    "5. Update `wrangler.jsonc` bindings and run `pnpm deploy:dry-run` before deploy.",
    "",
  ].join("\n"),
);

console.log(`Backup drill report: ${report}`);

function step(name, fn) {
  try {
    fn();
    steps.push(`${name}: ok`);
  } catch (error) {
    steps.push(`${name}: failed`);
    writeFileSync(
      report,
      `# FlareMo Backup Drill\n\nFailed step: ${name}\n\n${String(error)}\n`,
    );
    throw error;
  }
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    encoding: "utf8",
    stdio: options.capture ? ["ignore", "pipe", "pipe"] : "inherit",
    shell: process.platform === "win32",
  });

  if (result.status !== 0) {
    if (options.capture) {
      process.stderr.write(result.stderr);
      process.stdout.write(result.stdout);
    }
    throw new Error(
      `${command} ${args.join(" ")} failed with exit code ${result.status}`,
    );
  }

  if (options.capture && result.stderr) {
    process.stderr.write(result.stderr);
  }

  return result;
}
